
/**
 * Global Configuration for Meta Pixel, Domain Verification, and Event Tracking (20 Pages).
 * DO NOT EDIT THIS FILE MANUALLY. It is generated by admin-config.html.
 */
const CONFIG_PAGES = [
    {
        "key": "FACEBOOK 1",
        "name": "Name 1",
        "pixelId": "1875036436680690",
        "domainVerification": "irbitds8t5nogsmssbgdfmjrila3oh",
        "eventTracking": []
    },
    {
        "key": "FACEBOOK 2",
        "name": "Name 2",
        "pixelId": "",
        "domainVerification": "",
        "eventTracking": []
    },
    {
        "key": "FACEBOOK 3",
        "name": "Name 3",
        "pixelId": "",
        "domainVerification": "",
        "eventTracking": []
    },
    {
        "key": "FACEBOOK 4",
        "name": "Name 4",
        "pixelId": "",
        "domainVerification": "",
        "eventTracking": []
    },
    {
        "key": "FACEBOOK 5",
        "name": "Name 5",
        "pixelId": "",
        "domainVerification": "",
        "eventTracking": []
    },
    {
        "key": "FACEBOOK 6",
        "name": "Name 6",
        "pixelId": "",
        "domainVerification": "",
        "eventTracking": []
    },
    {
        "key": "FACEBOOK 7",
        "name": "Name 7",
        "pixelId": "",
        "domainVerification": "",
        "eventTracking": []
    },
    {
        "key": "FACEBOOK 8",
        "name": "Name 8",
        "pixelId": "",
        "domainVerification": "",
        "eventTracking": []
    },
    {
        "key": "FACEBOOK 9",
        "name": "Name 9",
        "pixelId": "",
        "domainVerification": "",
        "eventTracking": []
    },
    {
        "key": "FACEBOOK 10",
        "name": "Name 10",
        "pixelId": "",
        "domainVerification": "",
        "eventTracking": []
    },
    {
        "key": "FACEBOOK 11",
        "name": "Name 11",
        "pixelId": "",
        "domainVerification": "",
        "eventTracking": []
    },
    {
        "key": "FACEBOOK 12",
        "name": "Name 12",
        "pixelId": "",
        "domainVerification": "",
        "eventTracking": []
    },
    {
        "key": "FACEBOOK 13",
        "name": "Name 13",
        "pixelId": "",
        "domainVerification": "",
        "eventTracking": []
    },
    {
        "key": "FACEBOOK 14",
        "name": "Name 14",
        "pixelId": "",
        "domainVerification": "",
        "eventTracking": []
    },
    {
        "key": "FACEBOOK 15",
        "name": "Name 15",
        "pixelId": "",
        "domainVerification": "",
        "eventTracking": []
    },
    {
        "key": "FACEBOOK 16",
        "name": "Name 16",
        "pixelId": "",
        "domainVerification": "",
        "eventTracking": []
    },
    {
        "key": "FACEBOOK 17",
        "name": "Name 17",
        "pixelId": "",
        "domainVerification": "",
        "eventTracking": []
    },
    {
        "key": "FACEBOOK 18",
        "name": "Name 18",
        "pixelId": "",
        "domainVerification": "",
        "eventTracking": []
    },
    {
        "key": "FACEBOOK 19",
        "name": "Name 19",
        "pixelId": "",
        "domainVerification": "",
        "eventTracking": []
    },
    {
        "key": "FACEBOOK 20",
        "name": "Name 20",
        "pixelId": "",
        "domainVerification": "",
        "eventTracking": []
    }
];

/**
 * INJECTOR FUNCTION: Finds config based on data-config-key in body tag and injects Meta/FB Pixel.
 */
function injectMetaTags() {
    const bodyConfigName = document.body.getAttribute('data-config-key');
    
    if (!bodyConfigName) {
        console.warn('Meta Config: Body attribute "data-config-key" not found. Cannot inject specific Pixel/Domain.');
        return;
    }

    const pageConfig = CONFIG_PAGES.find(config => config.key === bodyConfigName);
    
    if (!pageConfig || !pageConfig.pixelId || !pageConfig.domainVerification) {
        console.error('Meta Config: Configuration not found or incomplete for key:', bodyConfigName);
        return;
    }

    const PIXEL_ID = pageConfig.pixelId;
    const DOMAIN_ID = pageConfig.domainVerification;
    
    // 1. Inject Domain Verification Meta Tag
    const domainMeta = document.createElement('meta');
    domainMeta.name = 'facebook-domain-verification';
    domainMeta.content = DOMAIN_ID;
    document.head.prepend(domainMeta);
    
    // 2. Inject Meta Pixel Base Code (Standard Setup)
    const pixelCode = `
    !function(f,b,e,v,n,t,s)
    {if(f.fbq)return;n=f.fbq=function(){n.callMethod?
    n.callMethod.apply(n,arguments):n.queue.push(arguments)};
    if(!f._fbq)f._fbq=n;n.push=n;n.loaded=!0;n.version='2.0';
    n.queue=[];t=b.createElement(e);t.async=!0;
    t.src=v;s=b.getElementsByTagName(e)[0];
    s.parentNode.insertBefore(t,s)}(window, document,'script',
    'https://connect.facebook.net/en_US/fbevents.js');
    fbq('init', '${PIXEL_ID}');
    fbq('track', 'PageView');
    `;
    
    const pixelScript = document.createElement('script');
    pixelScript.textContent = pixelCode;
    document.head.appendChild(pixelScript);
    
    // Inject noscript tag
    const noscriptDiv = document.createElement('noscript');
    noscriptDiv.innerHTML = `<img height="1" width="1" style="display:none" src="https://www.facebook.com/tr?id=${PIXEL_ID}&ev=PageView&noscript=1" />`;
    document.head.appendChild(noscriptDiv);
    
    console.log(`Meta Config: Injected ID ${PIXEL_ID} for page key ${bodyConfigName} (${pageConfig.name})`);

    // 3. Attach Event Listeners
    attachEvents(pageConfig.eventTracking);
}

function attachEvents(eventTrackingConfig) {
    if (!eventTrackingConfig || eventTrackingConfig.length === 0) {
        return; 
    }
    
    document.addEventListener('DOMContentLoaded', () => {
        if (!window.fbq) {
             console.warn('FBQ not available for event attachment.');
             return;
        }
        
        eventTrackingConfig.forEach(config => {
            const element = document.querySelector(`[data-fb-event-id="${config.id}"]`);
            if (element) {
                element.addEventListener('click', (e) => {
                    config.events.forEach(event => {
                        window.fbq('track', event.name, event.params || {});
                        console.log('FB Event Tracked:', event.name, 'for ID:', config.id);
                    });
                });
            } else {
                console.warn('FB Event Config Warning: Element not found for ID:', config.id);
            }
        });
    });
}


// Automatically call the injection function
injectMetaTags();
